# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cd67b649835563796b57b834ce012c5bc975ae20a30fa167ed03d53ca9f1183d29bff3d803d7feefe72f518d89861ead3a1d53ff15756423850174a7212d875

test:
  secret_key_base: 9f29c0a38f25687d2f14d28d721d5525bd56077bfb0e71047ca11606ccd689775af0c240ac0af6307c8ee563cc818dde6358f37ea41e147e195c50346a03600e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
